redis:
  image: redis
  container_name: cache
  expose:
    - 6379
  ports:
    - 6379:6379
app:
  build: ./
  volumes:
    - ./:/var/www/app
  links:
    - redis
  ports:
    - 3000:3000
  environment:
    - REDIS_URL=redis://cache
    - NODE_ENV=development
    - PORT=3000
  entrypoint:
    - /usr/local/bin/docker-entrypoint.sh

