version: '2.1'

services:
  redis:
    build: ./redis
    container_name: cache
    expose:
      - 6379
    ports:
      - 6379:6379

  app:
    depends_on:
      - redis
    build: ./
    command: ["-c", "/opt/wait-for-redis.sh cache 6379 && npm run start-docker"]
    entrypoint: ["/bin/sh"]
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3000:3000

